# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    use_super_parameters: true
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

dart_code_metrics:
  rules:
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-wrapping-in-padding
    - avoid-banned-imports:
        entries:
          - paths: [".*/domain/.*\\.dart"]
            deny: [".*/data/.*\\.dart", ".*/ui/.*\\.dart", "package:flutter*"]
            message: "Do not import following: data layer, ui layer, third-party or Flutter references into domain as it voilates DDD rules!"
          - paths: [".*/core/.*\\.dart"]
            deny: [".*/features/.*\\.dart", ".*/ui/.*\\.dart"]
            message: "Importing features and ui layer into core is not allowed, only other way around"
          - paths: [".*/features/.*\\.dart"]
            deny: [".*/ui/.*\\.dart"]
            message: "Importing ui layer into features is not allowed!"
          - paths: [".*/ui/.*\\.dart"]
            deny: [".*/data/.*\\.dart"]
            message: "Importing data layer into ui layer is not allowed!"
        severity: error (edited)
